### ISSUE TITLE
document that udev + network_mode: host causes modem issues

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/docs#956]
It seems that the combination of udev and `network_mode: host` causes cellular modems to be replugged after a container restart, which often will result in the modem never reconnecting.

The recommendation for modem based applications is to use a `microservices` application type and add a `docker-compose.yml` that looks as follows:

```
version: '2.1'
networks: {}
volumes:
  resin-data: {}
services:
  main:
    build:
      context: .
    privileged: true
    restart: always
    # network_mode: host
    volumes:
      - 'resin-data:/data'
    labels:
      io.resin.features.kernel-modules: '1'
      io.resin.features.firmware: '1'
      io.resin.features.dbus: '1'
      io.resin.features.supervisor-api: '1'
      io.resin.features.resin-api: '1'
```

the reason has to do with https://github.com/systemd/systemd/issues/6713 and the way udev in the container handles network namespaces.
